[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
ethrex-vm.workspace = true
ethrex-prover.workspace = true
ethrex-l2.workspace = true
ethrex-rpc-client.workspace = true

zkvm_interface = { path = "../zkvm/interface", default-features = false }
tokio = { version = "1.21", default-features = false, features = ["full"] }
clap = { version = "4.5.21", features = ["derive"] }
bincode = "1.3.3"

[features]
## risc0
build_risc0 = ["zkvm_interface/build_risc0", "ethrex-prover/build_risc0"]
gpu = ["ethrex-prover/gpu"]
## sp1
build_sp1 = ["zkvm_interface/build_sp1", "zkvm_interface/build_risc0"]
