[package]
name = "ethrex-prover"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json.workspace = true
serde.workspace = true
bytes.workspace = true
ethereum-types.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
hex.workspace = true
thiserror.workspace = true

# ethrex
ethrex-common.workspace = true
ethrex-vm.workspace = true
ethrex-rlp.workspace = true

# l2
ethrex-l2.workspace = true

zkvm_interface = { path = "./zkvm/interface", default-features = false }

# risc0
risc0-zkvm = { version = "1.2.2", optional = true }

# sp1
sp1-sdk = "4.1.0"

# sp1
pico-sdk = { git = "https://github.com/brevis-network/pico", optional = true }

[dev-dependencies]
ethrex-vm.workspace = true
ethrex-storage.workspace = true
ethrex-blockchain.workspace = true

[lib]
name = "ethrex_prover_lib"
path = "src/lib.rs"

[[bin]]
name = "ethrex_prover"
path = "src/main.rs"

[features]
default = []
build_risc0 = ["zkvm_interface/build_risc0", "dep:risc0-zkvm"]
build_sp1 = ["zkvm_interface/build_sp1"]
build_pico = ["zkvm_interface/build_pico", "ethrex-l2/pico", "dep:pico-sdk"]
sp1 = []
pico = []
risc0 = []
l2 = ["ethrex-vm/l2"]                                                        # the prover can work with both l1 or l2 blocks
gpu = ["risc0-zkvm/cuda", "sp1-sdk/cuda"]

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
as_conversions = "deny"
unnecessary_cast = "warn"
panic = "deny"
