[workspace]
resolver = "2"
members = [
    "crates/consensus",
    "crates/core",
    "crates/evm",
    "crates/net",
    "crates/rpc",
    "crates/storage",
]

[workspace.package]
name = "ethereum_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
sha3 = "0.10.8"
fastrlp = "0.3.1"
enr = { version = "0.12.0", features = ["rust-secp256k1"] }
