[package]
name = "ethrex-l2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
ethereum-types.workspace = true
ethrex-common.workspace = true
ethrex-rlp.workspace = true
ethrex-rpc.workspace = true
ethrex-blockchain.workspace = true
ethrex-storage.workspace = true
ethrex-vm.workspace = true
ethrex-dev = { path = "../../crates/blockchain/dev" }
hex.workspace = true
bytes.workspace = true
jsonwebtoken.workspace = true
secp256k1.workspace = true
keccak-hash.workspace = true
envy = "0.4.2"
thiserror.workspace = true
directories = "5.0.1"

ethrex-sdk = { path = "./sdk" }

zkvm_interface = { path = "./prover/zkvm/interface/", default-features = false }

risc0-zkvm = { version = "1.2.2", optional = true }
sp1-sdk = { version = "4.1.0", optional = true }
pico-vm = { git = "https://github.com/brevis-network/pico", optional = true }

ethrex-metrics = { path = "../blockchain/metrics", default-features = false }

[dev-dependencies]
rand = "0.8.5"


[lib]
path = "./l2.rs"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
as_conversions = "deny"
unnecessary_cast = "warn"
panic = "deny"

[features]
default = []
metrics = ["ethrex-metrics/l2"]
pico = ["zkvm_interface/pico", "dep:pico-vm"]
risc0 = ["zkvm_interface/risc0", "dep:sp1-sdk"]
sp1 = ["zkvm_interface/sp1", "dep:risc0-zkvm"]
