participants:
  - el_type: ethrex
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v5.3.0
    validator_count: 22
  - el_type: geth
    el_image: ethereum/client-go:v1.14.12
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v5.3.0
    validator_count: 21
  - el_type: geth
    el_image: ethereum/client-go:v1.14.12
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v5.3.0
    validator_count: 21

additional_services:
  - assertoor
  - tx_spammer
  - dora

assertoor_params:
  image: ethpandaops/assertoor:v0.0.12
  run_stability_check: false
  run_block_proposal_check: false
  tests:
    - https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/stable/blob-transactions-test.yaml
    - https://raw.githubusercontent.com/lambdaclass/ethrex/refs/heads/main/.github/config/assertoor/el-stability-check.yaml

tx_spammer_params:
  tx_spammer_extra_args: ["--txcount=3", "--accounts=80"]
