[package]
name = "ethereum-p2p"
version.workspace = true
edition.workspace = true

[dependencies]
# Tracing
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3.0", features = ["env-filter"] }

# Networking
tokio = { version = "1.43.0", features = ["full"] }
tokio-util = { version = "0.7.13" }

# Error handling
thiserror = "2.0.11"

# Ethereum
ethrex-rlp.workspace = true
ethrex-core.workspace = true

# Cryptography
libsecp256k1 = { version = "0.7.1", features = ["std"] }
secp256k1 = { version = "0.29", default-features = false, features = [
    "global-context",
    "recovery",
    "rand",
] }
aes = "0.8.3"
ctr = "0.9.2"
hmac = "0.12.1"
k256 = { version = "0.13.3", features = ["ecdh"] }
concat-kdf = "0.1.0"


# Serialization
serde_json = "1.0.137"

keccak-hash.workspace = true
bytes = "1.9.0"
rand = "0.8.5"
hex = "0.4.3"

commonware-runtime = "0.0.14"

[lints]
# workspace = true

[[example]]
name = "discovery"
path = "examples/discovery.rs"

[[example]]
name = "rlpx_initiator"
path = "examples/rlpx_initiator.rs"

[[example]]
name = "rlpx_receiver"
path = "examples/rlpx_receiver.rs"
