[package]
name = "ethereum_rust-blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
ethereum_rust-core.workspace = true
ethereum_rust-rlp.workspace = true
ethereum_rust-storage.workspace = true
ethereum_rust-evm.workspace = true
sha3.workspace = true


[lib]
path = "./blockchain.rs"

[features]
default = ["libmdbx"]
no_libmdbx = ["ethereum_rust-core/no_libmdbx", "ethereum_rust-storage/no_libmdbx", "ethereum_rust-evm/no_libmdbx"]
libmdbx = ["ethereum_rust-core/libmdbx", "ethereum_rust-storage/libmdbx", "ethereum_rust-evm/libmdbx"]
