[package]
name = "zkvm-pico-program"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
pico-sdk = { git = "https://github.com/brevis-network/pico" }
zkvm_interface = { path = "../" }

ethrex-core = { path = "../../../../../common", default-features = false }
ethrex-rlp = { path = "../../../../../common/rlp" }
ethrex-vm = { path = "../../../../../vm", default-features = false }
ethrex-blockchain = { path = "../../../../../blockchain", default-features = false }
