[package]
name = "revm_comparison"
version = "0.1.0"
edition = "2021"

[lib]
name = "revm_comparison"
path = "src/lib.rs"

[dependencies]
ethrex-levm = { path = "../../" }
ethrex-vm = { path = "../../../" }
ethrex-rpc-client.workspace = true
hex.workspace = true
bytes.workspace = true

revm = "9.0.0"
sha3 = "0.10.8"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
bincode = "1.3.3"

[[bin]]
name = "compile"
path = "src/compile.rs"

[[bin]]
name = "benchmark"
path = "src/benchmark.rs"

[[bin]]
name = "benchmark-block"
path = "src/benchmark_block.rs"
